Repository Kaiser-Yang/matrix-calculation-accelerator, pull requests merged in 2024-06, with the labels that each got.

#106 Finish tasks of multi thread calculations
  src/include/mca/mca.h
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: new feature or unit test

#109 Refactor matrix to remove memory wastes and to reuse codes
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
  src/include/mca/matrix.h
  src/thread_pool.cpp
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: enhancement

#111 Add iterators and some member types
  src/include/mca/__mca_internal/matrix_declaration.h
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
  src/include/mca/__mca_internal/thread_pool.h
  src/include/mca/diag.h
  src/include/mca/matrix.h
  src/include/mca/mca.h
  src/include/mca/shape.h
  src/thread_pool.cpp
  test/src/different_type_test.cpp
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/same_address_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: enhancement

#114 Add methods to judge symmetric and antisymmetric
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
  src/include/mca/matrix.h
  test/src/multi_thread_matrix_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#116 Add a class called CalculationTaskNum
  src/include/mca/__mca_internal/calculation_task_num.h
  src/include/mca/matrix.h
  src/include/mca/mca.h
Labels: enhancement

#117 Update some methods of multi thread
  .github/workflows/cmake-multi-platform.yml
  src/include/mca/matrix.h
  src/include/mca/mca.h
  src/thread_pool.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: bug, new feature or unit test

#121 Add directories of examples and docs
  .github/workflows/clang-format.yml
  CMakeLists.txt
  README.md
  codecov.yml
  doc/en/developer/index.md
  doc/en/user/buildAndInstall.md
  doc/en/user/index.md
  doc/zh/developer/index.md
  doc/zh/user/index.md
  example/include/example_utility.h
  example/matrix_construction.cpp
Labels: documentation

#126 Add clang-format git action
  .github/workflows/clang-format.yml
  README.md
Labels: new feature or unit test
