Repository Kaiser-Yang/matrix-calculation-accelerator, pull requests merged in 2024-07, with the labels that each got.

#136 Finish refactoring the calculation
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
  src/include/mca/__mca_internal/utility.h
  src/include/mca/matrix.h
  src/include/mca/mca.h
  src/mca_config.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: enhancement/refactor

#137 Finish documents
  .gitignore
  doc/en/user/buildAndInstall.md
  doc/en/user/diag.md
  doc/en/user/identityMatrix.md
  doc/en/user/index.md
  doc/en/user/matrix.md
  doc/en/user/mca.md
  doc/en/user/shape.md
  example/matrix_construction.cpp
  src/include/mca/matrix.h
  src/include/mca/mca.h
  src/include/mca/shape.h
  test/src/matrix_test.cpp
Labels: documentation

#138 Add documents for mca configurations
  doc/en/user/index.md
  doc/en/user/mca.md
  doc/en/user/mcaConfig.md
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
Labels: documentation

#139 Add some documents for developers
  CMakeLists.txt
  README.md
  doc/en/developer/codeSubmit.md
  doc/en/developer/codeWrite.md
  doc/en/developer/index.md
  doc/en/developer/projectBuild.md
  doc/en/user/buildAndInstall.md
  doc/en/user/index.md
  test/CMakeLists.txt
Labels: documentation

#141 Add some examples of the matrix documents
  doc/en/user/matrix.md
  example/include/example_utility.h
  example/matrix_construction.cpp
  example/matrix_iterator.cpp
  example/matrix_operation.cpp
  example/matrix_other.cpp
Labels: documentation

#142 Bump up version to v0.2.0
  README.md
  doc/en/CHANGE_LOG.md
Labels: release

#143 Release v0.2.0
  .clang-format
  .github/workflows/clang-format.yml
  .github/workflows/cmake-multi-platform.yml
  .github/workflows/codecov-action.yml
  .github/workflows/codecov-on-develop.yml
  .github/workflows/codecov-on-master.yml
  .gitignore
  CMakeLists.txt
  README.md
  codecov.yml
  doc/en/CHANGE_LOG.md
  doc/en/developer/codeSubmit.md
  doc/en/developer/codeWrite.md
  doc/en/developer/index.md
  doc/en/developer/projectBuild.md
  doc/en/user/buildAndInstall.md
  doc/en/user/diag.md
  doc/en/user/identityMatrix.md
  doc/en/user/index.md
  doc/en/user/matrix.md
  doc/en/user/mca.md
  doc/en/user/mcaConfig.md
  doc/en/user/shape.md
  doc/zh/developer/index.md
  doc/zh/user/index.md
  example/include/example_utility.h
  example/matrix_construction.cpp
  example/matrix_iterator.cpp
  example/matrix_operation.cpp
  example/matrix_other.cpp
  example/mca_examples.cpp
  src/include/matrix.h
  src/include/mca.h
  src/include/mca/__mca_internal/calculation_task_num.h
  src/include/mca/__mca_internal/matrix_declaration.h
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
  src/include/mca/__mca_internal/thread_pool.h
  src/include/mca/__mca_internal/utility.h
  src/include/mca/diag.h
  src/include/mca/identity_matrix.h
  src/include/mca/matrix.h
  src/include/mca/mca.h
  src/include/mca/mca_config.h
  src/include/mca/shape.h
  src/include/single_thread_matrix_calculation.h
  src/include/thread_pool.h
  src/mca.cpp
  src/mca_config.cpp
  src/thread_pool.cpp
  test/CMakeLists.txt
  test/src/different_type_test.cpp
  test/src/matrix_test.cpp
  test/src/mca_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/same_address_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
  test/src/thread_pool_test.cpp
Labels: release

#144 Bump version up to v0.2.1
  .github/workflows/clang-format.yml
  doc/en/CHANGE_LOG.md
  doc/en/developer/projectBuild.md
Labels: bug

#145 Fix v0.2.1
  .github/workflows/clang-format.yml
  doc/en/CHANGE_LOG.md
  doc/en/developer/projectBuild.md
Labels: bug
