Repository Kaiser-Yang/matrix-calculation-accelerator, pull requests merged in 2024-05, with the labels that each got.

#18 Finish some tests for single thread calculation
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
  test/src/single_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#21 Add a thread pool and finish the unit test
  .clang-tidy
  .github/workflows/cmake-multi-platform.yml
  CMakeLists.txt
  include/mca.h
  src/include/mca.h
  src/include/thread_pool.h
  src/mca.cpp
  src/thread_pool.cpp
  test/CMakeLists.txt
  test/src/thread_pool_test.cpp
Labels: new feature or unit test

#26 Feature zzq unit test single thread
  CMakeLists.txt
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
  test/src/single_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#30 Update git actions
  .codecov.yml
  .github/workflows/cmake-multi-platform.yml
  .github/workflows/codecov-action.yml
  .github/workflows/codecov-on-develop.yml
  .github/workflows/codecov-on-master.yml
Labels: new feature or unit test

#31 Feature rename configure files
  codecov.yml
Labels: bug

#33 Update codecov config
  README.md
  codecov.yml
Labels: bug

#29 Fix git action failed on Windows when building shared library
  .github/workflows/cmake-multi-platform.yml
  CMakeLists.txt
  test/CMakeLists.txt
Labels: bug

#37 Finish some test for single thread
  test/src/single_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#39 Finish some test for the single thread.
  test/src/single_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#42 Fix the `url` of `codecov`
  README.md
Labels: bug

#43 Hotfix v0.1.1
  README.md
Labels: bug

#44 Hotfix v0.1.2
  README.md
Labels: bug

#45 Add titles of figures
  README.md
Labels: bug

#47 Fix clang tidy
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
  src/include/thread_pool.h
  test/src/different_type_test.cpp
  test/src/thread_pool_test.cpp
Labels: bug

#49 Add an example to show how to use thread pool
  src/include/matrix.h
  src/include/mca.h
  src/include/thread_pool.h
  src/mca.cpp
  src/thread_pool.cpp
  test/CMakeLists.txt
  test/src/mca_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
  test/src/thread_pool_test.cpp
Labels: new feature or unit test

#51 Remove circular dependency by forward declaration
  src/include/matrix.h
  src/include/mca.h
Labels: bug

#53 Finish all the tasks and unit tests
  src/include/matrix.h
  src/include/mca.h
  src/include/single_thread_matrix_calculation.h
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: new feature or unit test

#55 Update the single thread implementations
  src/include/matrix.h
  src/include/mca.h
  src/include/single_thread_matrix_calculation.h
  test/src/different_type_test.cpp
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: bug

#59 Modify the sing thread calulation and test
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
  test/src/different_type_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: bug

#57 Update single thread functions with pos and len
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
  test/src/different_type_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: bug

#60 Update implementations of single thread
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
  test/src/different_type_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: bug

#62 Finish some tasks for the multi thread
  src/include/matrix.h
  src/include/mca.h
  src/include/single_thread_matrix_calculation.h
  test/src/different_type_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: new feature or unit test

#68 Fix a bug for Matrix::fill
  .clang-format
  src/include/matrix.h
  src/include/single_thread_matrix_calculation.h
Labels: bug

#69 Substitute single line comments with multi-line
  src/include/mca.h
  src/include/single_thread_matrix_calculation.h
Labels: documentation

#70 Add type traits for Number
  src/include/mca.h
  src/include/mca_utility.h
  src/include/single_thread_matrix_calculation.h
  test/src/mca_test.cpp
Labels: enhancement

#71 Substitute single line comments with multi-line
  src/include/matrix.h
Labels: documentation

#72 Finish multi thread calculation methods
  src/include/matrix.h
  src/include/mca.h
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: new feature or unit test

#75 Finish some multi-thread calculations
  src/include/matrix.h
  src/include/matrix_declaration.h
  src/include/mca.h
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: new feature or unit test

#76 Enhance unit tests
  src/include/matrix.h
  src/include/mca.h
  src/include/thread_pool.h
  src/thread_pool.cpp
  test/src/mca_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/thread_pool_test.cpp
Labels: bug, enhancement, new feature or unit test

#80 Update coverage reports build type
  .github/workflows/codecov-action.yml
  .github/workflows/codecov-on-develop.yml
  .github/workflows/codecov-on-master.yml
  test/src/multi_thread_matrix_test.cpp
Labels: enhancement

#84 Finish some multi-thread calculation methods
  src/include/mca.h
  test/src/multi_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#91 Add explicit for some constructors
  src/include/matrix.h
  test/src/different_type_test.cpp
  test/src/matrix_test.cpp
  test/src/same_address_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
Labels: enhancement

#88 Finish some tasks of multi thread
  src/include/mca.h
  test/src/multi_thread_matrix_calculation_test.cpp
Labels: new feature or unit test

#94 Add a class called IdentityMatrix
  src/include/identity_matrix.h
  src/include/matrix.h
  src/include/matrix_declaration.h
  src/include/mca.h
  src/include/shape.h
  src/include/single_thread_matrix_calculation.h
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: enhancement

#99 Add a class called Diag
  src/include/diag.h
  src/include/identity_matrix.h
  src/include/matrix.h
  src/include/shape.h
  test/src/matrix_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: enhancement

#97 Fix the bug about eps and the greater signs
  src/include/mca.h
Labels: bug

#93 Finish some tasks of multi thread
  src/include/matrix.h
  src/include/mca.h
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
Labels: new feature or unit test

#102 Update the structure of header files
  .github/workflows/cmake-multi-platform.yml
  .github/workflows/codecov-action.yml
  .github/workflows/codecov-on-develop.yml
  .github/workflows/codecov-on-master.yml
  CMakeLists.txt
  README.md
  src/include/mca/__mca_internal/matrix_declaration.h
  src/include/mca/__mca_internal/single_thread_matrix_calculation.h
  src/include/mca/__mca_internal/thread_pool.h
  src/include/mca/__mca_internal/utility.h
  src/include/mca/diag.h
  src/include/mca/identity_matrix.h
  src/include/mca/matrix.h
  src/include/mca/mca.h
  src/include/mca/shape.h
  src/mca.cpp
  src/thread_pool.cpp
  test/src/different_type_test.cpp
  test/src/matrix_test.cpp
  test/src/mca_test.cpp
  test/src/multi_thread_matrix_calculation_test.cpp
  test/src/multi_thread_matrix_test.cpp
  test/src/same_address_test.cpp
  test/src/single_thread_matrix_calculation_test.cpp
  test/src/thread_pool_test.cpp
Labels: enhancement
